/**
 * brand-config.ts
 *
 * Canonical brand names and junk-brand patterns shared by
 * sync-to-supabase.ts and cleanup-brands.ts.
 *
 * Canonical casing: the string here is what ends up in the DB.
 * Matching is case-insensitive prefix against the product name.
 */

// ---------------------------------------------------------------------------
// Junk brand patterns — products matching these get brand = null
// ---------------------------------------------------------------------------

export const JUNK_BRAND_PATTERNS = [
  /^\s/,              // leading whitespace ("  B", "  (CIEM-)")
  /^[^a-zA-Z0-9]/,   // starts with non-alphanumeric ("-------", "*", "*EQ", "<Clone>")
  /^\[/,              // "[IEMs]", "[Unbranded]"
];

export const JUNK_BRANDS_EXACT = new Set([
  '-SAMPLE-',
  'Sample',
  'Test',
  'TEST',
  'Testing',
  'Testarea',
  'Temp',
  'Unknown',
  'UNKNOWN',
  'NOTBRAND',
  'Brand',
  'Other',
  'Custom',
  'Prototype',
  'Service',
  'Cable',
  'Earphone',
  'Ear',
  'DAC',
  'E',
  'T',
  'HZ',
  'HP',
  'HS',
  'KG',
  'SG',
  'NS',
  'UK',
  'In',
  'Air',
  'One',
  'Moon',
  'fix',
  'Fat',
  'Flo',
  'Db',
  'KB',
  'OB',
  'MX',
  'FZ',
  'ES',
  'NC',
  'TH',
  'GS',
  'JD',
  'LH',
  'ND',
  'NF',
  'Ag',
  'Tin',        // "Tin" alone is fallback; real brand is "Tin HiFi"
  'Sound',      // "Sound" alone is fallback; real brands are "SoundMAGIC", etc.
  'Audio',      // "Audio" alone is fallback; real brands are "Audio-Technica", etc.
  'AUDIO',
  'Open',       // "Open" alone is fallback
  'Acoustic',
  'ACOUSTIC',
  'Gold',
  'GOLD',
  'Night',
  'NIGHT',
  'Rose',       // "Rose" alone is fallback; real brand is "RoseSelsa", etc.
  'ROSE',
  'Sonic',
  'Music',
  'Light',
  'Rock',
  'Ice',
  'ICE',
  'Seek',
  'SEEK',
  'Spiral',
  'SPIRAL',
  'Spirit',
  'SPIRIT',
  'Project',
  'PROJECT',
  'Effect',
  'EFFECT',
  'Melody',
  'MELODY',
  'Guide',
  'Halo',
  'Master',
  'Top',
  'Neo',
  'Zen',
  'Zhe',
  'Pai',
  'Neng',
  'Lark',
  'Vento',
  'BIG',
  'BIA',
  'DNA',
  'MDS',
  'TAP',
  'SIA',
  'MCA',
  'NCM',
  'TWX',
  'TXN',
  'ITK',
  'ORB',
  'ILit',
  'House',
  'Morph',
  'Swing',
  'Mark',
  'King',
  'Dope',
  'Oreo',
  'Wong',
  'Zhu',
  'Cat',
  'Jade',
  'JADE',
  'Thor',
  'THOR',
  'Focus',
  'FOCUS',
  'Alpha',
  'ALPHA',
  'Delta',
  'Metal',
  'Forte',
  'Clear',
  'Grand',
  'Secret',
  'SECRET',
  'Nature',
  'NATURE',
  'Bamboo',
  'BAMBOO',
  'Warbler',
  'WARBLER',
  'Harman',
  'HARMAN',
  'Anthem',
  'Dynamic',
  'Original',
  'Singapore',
  'Singaporean',
  'American',
  'Airlines',
  'Airline',
  'LATAM',
  'Thai',
  'Etihad',
  'Pioneer',  // not the audio brand in this context — it's fallback first-word
  'PIONEER',
  'The',
  'THE',
  'Mr',
  'MR',
  'Mr.',
  'David',
  'Jerry',
  'Allen',
  'Meyer',
  'Foster',
  'Lee\'s',
  'Flat',
  'Flathead',
  'Reference',
  'HiFi',
  'SWEATSHOP',
  'CALCINI',
]);

export function isJunkBrand(brand: string): boolean {
  if (JUNK_BRANDS_EXACT.has(brand)) return true;
  const trimmed = brand.trim();
  if (trimmed.length <= 2 && !/^\d/.test(trimmed)) return true; // single/double letter brands
  for (const pat of JUNK_BRAND_PATTERNS) {
    if (pat.test(brand)) return true;
  }
  return false;
}

// ---------------------------------------------------------------------------
// Canonical brand names
// ---------------------------------------------------------------------------
// Every entry here is used for prefix-matching (case-insensitive) against
// the product name. The first match wins, so longer names are sorted first
// at runtime.

export const KNOWN_BRANDS: string[] = [
  // ---- A ----
  '1Custom',
  '1Mii',
  '1More',
  '3APLUS',
  '3ESTATS',
  '4Acoustic',
  '4th',
  '634ears',
  '64 Audio',
  '7Hz',
  '7Hz-Salnotes',
  '7th',
  'A&D',
  'A&K',
  'AAW',
  'Abyss',
  'Accoustone',
  'Acefast',
  'Acoustune',
  'Activo',
  'Adam',
  'Adastra',
  'ADV',
  'Advanced',
  'AFUL',
  'Agasound',
  'AIAIAI',
  'Aiderlot',
  'Aiwa',
  'AKG',
  'Akoustyx',
  'Akros',
  'Alclair',
  'Alessandro',
  'Aliexpress',
  'Allway',
  'ALO',
  'Alpex',
  'Altec',
  'Altiat',
  'Ambient',
  'AME',
  'AngelEars',
  'Angelsound',
  'Angry',
  'Anker',
  'Antlion',
  'Aolon',
  'Aoshida',
  'Apcs',
  'Apevoix',
  'Apex',
  'Apos',
  'Apple',
  'ARC',
  'Archisound',
  'Arisyn',
  'Aroma',
  'ArpegEar',
  'ARRTI',
  'Artio',
  'Artiste',
  'Artpical',
  'Artti',
  'Ashida',
  'Ashidavox',
  'Astell&Kern',
  'Astell',
  'ASTRO',
  'Astrotec',
  'at.Q',
  'Atomic',
  'Atvel',
  'ATWO',
  'Audeze',
  'Audient',
  'Audiocular',
  'AudioDream',
  'Audiofly',
  'AudioQuest',
  'AudioSense',
  'Audio-Technica',
  'Auglamour',
  'Aukey',
  'AUNE',
  'Aure',
  'Aurisonics',
  'Aurorus',
  'Aür',
  'Austrian Audio',
  'Avara',
  'AVIOT',
  'Aya',
  'AWEI',
  'AZLA',
  // ---- B ----
  'B&O',
  'B&W',
  'Bamboo',
  'Bang&Olufsen',
  'Bang',
  'Baseus',
  'BASN',
  'Beamcrez',
  'Beats',
  'BEEMIX',
  'Beep',
  'Behringer',
  'Belkin',
  'Bellos',
  'Beyerdynamic',
  'BFB',
  'BGVP',
  'Binary',
  'Bleqk',
  'BLON',
  'BMani',
  'Boat',
  'Boltune',
  'BONAKO',
  'Bose',
  'Bowers',
  'BQEYZ',
  'Brainwavz',
  'Brianfay',
  'Brise',
  'Bujeon',
  'BUSAX',
  // ---- C ----
  'Cambridge',
  'Campfire Audio',
  'Canal',
  'CanalWorks',
  'Canpur',
  'Cardas',
  'CatEar',
  'Catbling',
  'Catchear',
  'Cayin',
  'CCA',
  'CCZ',
  'Celest',
  'CHEER',
  'Chikyu-Sekai',
  'Chikyu',
  'CHIKYUU-SEKAI',
  'CHIKYUU',
  'CKLVX',
  'Clariar',
  'Clavelon',
  'Cleer',
  'CMF',
  'Co-Donguri',
  'Colorfly',
  'Commo',
  'Cooler',
  'Cowon',
  'Cozoy',
  'Craft',
  'CraftEars',
  'Creative',
  'Cresyn',
  'CrinEar',
  'CrinEars',
  'Crossroads',
  'CTM',
  'Cutbox',
  'CVJ',
  'Cyberdrive',
  // ---- D ----
  'Daiso',
  'Dan Clark Audio',
  'Daruma',
  'Day6',
  'DBE',
  'DCA',
  'DDHiFi',
  'Debauche',
  'Delight',
  'Denon',
  'Dethonray',
  'Devialet',
  'DIREM',
  'Dita',
  'DIY',
  'DonCo',
  'Dove',
  'DQSM',
  'DRESSAGE',
  'Drop',
  'DUNU',
  'Dyson',
  'DZAT',
  // ---- E ----
  'E-MU',
  'EarAcoustic',
  'EarAcoustics',
  'EarBridge',
  'EarFun',
  'Earmax',
  'EARNiNE',
  'Earsonics',
  'Eartech',
  'ECCI',
  'Echobox',
  'Ecoustic',
  'écoute',
  'Edifier',
  'EDL',
  'EKaudio',
  'EKSA',
  'Elecom',
  'Elysian',
  'Eminent',
  'Empire Ears',
  'Endless',
  'Enigma',
  'Epicaudio',
  'EPOS',
  'EPZ',
  'EQ',
  'Eternal',
  'Etymotic',
  'Eva',
  'EZAudio',
  'EZEAR',
  // ---- F ----
  'Faaeal',
  'Faith',
  'FakeNemesis',
  'FATfreq',
  'FatFrequency',
  'FAudio',
  'Fearless',
  'Feaulle',
  'Fender',
  'Fengru',
  'Fidue',
  'Fifine',
  'FIIL',
  'FiiO',
  'Final',
  'fineEars',
  'FiR',
  'Fischer',
  'FitEar',
  'FLARE',
  'FLC',
  'Flicker-Ears',
  'Flicker',
  'FlipEars',
  'FloAudio',
  'Focal',
  'Fonge',
  'Fosi',
  'Fostex',
  // ---- G ----
  // G.K handled by alias → GK
  'G-Most',
  'Gaudio',
  'Geek',
  'Geekfly',
  'Geekwold',
  'GeekWorld',
  'Genesis',
  'GEVO',
  'Gizaudio',
  'GK',
  'GLIDiC',
  'GoldPlanar',
  'Grado',
  'Gravastar',
  'Grell',
  'GSound',
  'GuideRay',
  // ---- H ----
  'HAKII',
  'Hakugei',
  'HarmonicDyne',
  'HarmonicEmpire',
  'Harmonic',
  'HAVIT',
  'Haylou',
  'Hear+Hi',
  'Heartfield',
  'Heavys',
  'HEDD',
  'Heir',
  'Hercules',
  'HiBy',
  'Hidition',
  'Hidizs',
  'Hifiman',
  'Hifiboy',
  'Hi-Fri',
  'HiSenior',
  'Hmusic',
  'Horluchs',
  'Huawei',
  'HUM',
  'Humka',
  'Hyla',
  'HyperX',
  'HZSound',
  // ---- I ----
  'I-INTO',
  'I/O',
  'iBasso',
  'Icelabs',
  'Icelab',
  'iF',
  'iFi',
  'iHip',
  'IKKO',
  'IMR',
  'In2uit',
  'INAIR',
  'InAwaken',
  'InEar',
  'Inearz',
  'Ingping',
  'Initial',
  'INM',
  'Intaura',
  'Intime',
  'Intuaura',
  'IOAudio',
  'Iriver',
  'iSK',
  'ISN',
  'iSound',
  'ItsFit',
  'ivipQ',
  // ---- J ----
  'Jaben',
  'Jabra',
  'Jadeaudio',
  'Jaybird',
  'Jaybirds',
  'Jays',
  'JBL',
  'Jcally',
  'JH',
  'Jialai',
  'JiangSheng',
  'JLab',
  'JLL',
  'Jomo',
  'JoyAudio',
  'JoyOdio',
  'JPRiDE',
  'JQ',
  'Junex',
  'JuzEar',
  'JVC',
  // ---- K ----
  'K-array',
  'Kaiku',
  'Kanek',
  'Kataear',
  'KBEAR',
  'Kefine',
  'KEF',
  'Kennerton',
  'Kenwood',
  'Khastadio',
  'KiiBOOM',
  'Kinden',
  'Kinera',
  'KitSound',
  'KiwiEars',
  'Kiwi',
  'KKI',
  'Klipsch',
  'Koast',
  'Kojo',
  'Kontinum',
  'Koss',
  'Kotori',
  'Ksound',
  'Kumitate',
  'KZ',
  // ---- L ----
  'Lafitear',
  'LB-Acoustics',
  'LEAR',
  'Lefrig',
  'Leisurely',
  'Lenovo',
  'Leteciel',
  'LETSHUOER',
  'LG',
  'Libratone',
  'LimeEars',
  'Lime',
  'Linsoul',
  'Little',
  'Logitech',
  'LREY',
  'Lucid',
  'LUDOS',
  'LunSheng',
  'Lypertek',
  'LYEPERTEK',
  'LZ',
  // ---- M ----
  'M-Audio',
  'M&D',
  'MAaudio',
  'MacaW',
  'Mackie',
  'Madoo',
  'Maestraudio',
  'Magaosi',
  'Mangird',
  'Maono',
  'Marshall',
  'Massdrop',
  'Maxell',
  'MBQuart',
  'MCHOSE',
  'Meaoes',
  'Meccaudio',
  'Mechen',
  'MEE',
  'Meeaudio',
  'Meeture',
  'Meizu',
  'Melodic',
  'MelodyWings',
  'MEMT',
  'Metalure',
  'Meyr',
  'Meze',
  'Miida',
  'MiM',
  'Miniso',
  'Mixx',
  'MMR',
  'Modhouse',
  'Mofasest',
  'Moji',
  'Mondo',
  'Monoprice',
  'Monster',
  'Montblanc',
  'Moondrop',
  'Moritz',
  'Motorola',
  'MrSpeakers',
  'Mulazo',
  'Multilaser',
  'MUNITIO',
  'MuseHiFi',
  'Muse',
  'Mutex',
  'MUXICBOX',
  'Myer',
  'MYER-AUDIO',
  'Mystery',
  'Mysticraft',
  'Mystori',
  // ---- N ----
  'Naga',
  'NAGAOKA',
  'Nan-6',
  'NAN-Z',
  'Nectar',
  'Neumann',
  'Neuropunk',
  'Neusonik',
  'NFAcous',
  'NFAudio',
  'NFJ',
  'NGAudio',
  'NiceHCK',
  'Nice',
  'Nighjar',
  'Nightjar',
  'Noble',
  'NocturnaL',
  'Nokia',
  'Nostalgia',
  'Nothing',
  'Nuarl',
  'NuForce',
  'nura',
  'NXEars',
  // ---- O ----
  'oBravo',
  'Obafa',
  'Ocharaku',
  'OCTAVE',
  'Oddict',
  'OKCSC',
  'Oladance',
  'Ollo',
  'Omniwave',
  'Omthing',
  'OneOdio',
  'OnePlus',
  'Onkyo',
  'ooopusX',
  'OpenAudio',
  'Openheart',
  'Opera',
  'OPERAFACTORY',
  'Oppo',
  'Oriolus',
  'Oriveti',
  'Orivetti',
  'Ostry',
  'OURART',
  'Ovidius',
  // ---- P ----
  'PAA',
  'Padmate',
  'Padsmith',
  'PAIAudio',
  'Palavox',
  'Palma',
  'Panasonic',
  'Peacock',
  'PEARS',
  'Penon',
  'Pentaconn',
  'Periodic',
  'Phiaton',
  'Philips',
  'Phillips',
  'Phonak',
  'Plantronics',
  'Plexsonic',
  'PLEXTONE',
  'Plunge',
  'PlusSound',
  'PMGAudio',
  'PMG',
  'PMV',
  'Precide',
  'Primark',
  'Prisma',
  'PROfundo',
  'Pula',
  'Punch',
  // ---- Q ----
  'QCY',
  'qdc',
  'Qing',
  'QKZ',
  'QoA',
  'Quad',
  'Qudelix',
  'Queen',
  'Questyle',
  'Quidelix',
  'Quill',
  'Qveer',
  // ---- R ----
  'R2E3',
  'RAAL-requisite',
  'RAAL',
  'Radius',
  'RaptGo',
  'Raycon',
  'Razer',
  'Realfit',
  'Redeyes',
  'Redspace',
  'Reecho',
  'RevoNext',
  'RHA',
  'Rhapsodio',
  'Rockxxee',
  'Rode',
  'RØDE',
  'Rosenkranz',
  'RoseSelsa',
  'RoseTechnics',
  'Rossi',
  'Rosson',
  'RumAudio',
  'Ruviest',
  // ---- S ----
  'S&O',
  'Sabbat',
  'Salnotes',
  'Samsung',
  'Sange',
  'Sansui',
  'Saramonic',
  'SASH',
  'Satolex',
  'Seahf',
  'Seda',
  'SeeAudio',
  'SeekReal',
  'Semkarch',
  'Sendiy',
  'Sendy',
  'Senfer',
  'Sennheiser',
  'Senzer',
  'SGOR',
  'Shanling',
  'Shaner',
  'Shiro',
  'Shokz',
  'ShortBus',
  'Shozy',
  'Shuoer',
  'Shure',
  'Simgot',
  'Simphonio',
  'Sineaptic',
  'Singularity',
  'Sivga',
  'SKALD',
  'SKorea',
  'Skullcandy',
  'Sliivo',
  'Smabat',
  "Smirk's",
  'Snorry',
  'Snowy',
  'Snowy88',
  'Softears',
  'Soncie',
  'SonicMemory',
  'Sonicast',
  'Sonos',
  'SONY',
  'Soranik',
  'Soratune',
  'soundcore',
  'SoundMAGIC',
  'SoundPEATS',
  'SoundRhyme',
  'Soundz',
  'Spearlabs',
  'StageSound',
  'Status',
  'STAX',
  'Stealthsonics',
  'Steelseries',
  'StereoPravda',
  'Strauss',
  'Subtonic',
  'Sudio',
  'SuperEQ',
  'Superlux',
  'SuperTFZ',
  'Sweear',
  'Sweet',
  'Symphonium',
  'Symphonized',
  'Symphony',
  'SymphonyEars',
  // ---- T ----
  'T+A',
  // T-FORCE handled by alias → TForce
  'Tago',
  'TakeT',
  'Takstar',
  'Tanchjim',
  'Tanglaoshi',
  'Tangzu',
  'Tansio',
  'Taobao',
  'TCL',
  'TDK',
  'TDRH',
  'Technics',
  'Tecsun',
  'tekkusai',
  'Temperament',
  'Tenhz',
  'Tenii',
  'Tennmak',
  'TFZ',
  'THHiFi',
  'ThieAudio',
  'Thinksound',
  'Tiandirenhe',
  'Tigerism',
  'TimeEar',
  'TIMMKOO',
  'Timsok',
  'Tin HiFi',
  'Tingker',
  'Tinnitus',
  'Tipsy',
  'TKZK',
  'Toneking',
  'Tonemay',
  'Topping',
  'Tozo',
  'Tralucent',
  'Tranya',
  'Treckstor',
  'Trekstor',
  'TRI',
  'Trinity',
  'Tripowin',
  'TRN',
  'Tronsmart',
  'TrueFree',
  'Truthear',
  'TRZR',
  'TSMR',
  'TTR',
  'Turtle',
  'Turn',
  'Twistura',
  'TForce',
  // ---- U ----
  'Ucotech',
  'UFOEar',
  'Ugreen',
  'UiiSii',
  'Ultimate',
  'Ultrasone',
  'Unabridged',
  'UNCJC',
  'Unique',
  'United',
  'Urban',
  'UrbanFun',
  // ---- V ----
  'V-MODA',
  'Valco',
  'Valphonics',
  'VE',
  'Veedix',
  'Velodyne',
  'Venture',
  'VerseKeys',
  'Verum',
  'Victor',
  'Vido',
  'Vision',
  'Vison',
  'VJJB',
  'Volk',
  'VSonic',
  'Vzonis',
  // ---- W ----
  'W+G',
  'Warwick',
  'Wavelet',
  'WEMLIK',
  'Westone',
  'WGZBLON',
  'Whizzer',
  'Widing',
  'WLmouse',
  // ---- X ----
  'Xenns',
  'Xiaomi',
  'Xinhs',
  'Xingshenglong',
  'Xinsheng',
  'XK-Audio',
  'XK',
  'XROUND',
  'XSL',
  'Xuanerji',
  // ---- Y ----
  'Yamaha',
  'YanYin',
  'YimianHushui',
  'Yincrow',
  'Yinfu',
  'Yinman',
  'Yinyoo',
  'Yongse',
  'Yoshi',
  'Yuandao',
  'Yuin',
  'Yusicon',
  'YU9',
  'YS',
  // ---- Z ----
  'Z-Acoustics',
  'Zaylli',
  'ZEMPIREAUDIO',
  'Zempire',
  'Zero',
  'Zhewuyusheng',
  'Zhewu',
  'ZhuLinNiao',
  'ZiiGaat',
  'Ziigat',
  'Zildjian',
  'ZiSin',
  'ZigAat',
  'ZMF',
];

// ---------------------------------------------------------------------------
// Brand aliases — variant spellings that map to a canonical KNOWN_BRANDS entry
// ---------------------------------------------------------------------------
// Key: variant prefix (case-insensitive match), Value: canonical brand name.
// These are checked BEFORE the first-word fallback.

export const BRAND_ALIASES: Record<string, string> = {
  // 64 Audio variants
  '64audio': '64 Audio',
  // Audio-Technica variants
  'audiotechnica': 'Audio-Technica',
  'audio technica': 'Audio-Technica',
  // Campfire (without "Audio")
  'campfire': 'Campfire Audio',
  // See Audio / SeeAudio consolidation — both in KNOWN_BRANDS but we prefer SeeAudio
  'see audio': 'SeeAudio',
  // Tin HiFi / TinHiFi consolidation — prefer Tin HiFi
  'tinhifi': 'Tin HiFi',
  // T-FORCE / TForce consolidation
  't-force': 'TForce',
  // Hi-Fri / HiFri consolidation
  'hifri': 'Hi-Fri',
  // I/O variants
  'i\\o': 'I/O',
  'io': 'I/O',
  // Aür variants
  'aur': 'Aür',
  // SonicMemory with Chinese chars
  'sonicmemory(声音记忆)': 'SonicMemory',
  // Whizzer with Chinese chars
  'whizzer(威泽)': 'Whizzer',
  // FIIL with Chinese chars
  'fiil(斐耳)': 'FIIL',
  // 7Hz with Chinese chars
  '7hz(七赫兹)': '7Hz',
  // 7Hz(Salnotes) / 7Hz/Salnotes variants
  '7hz(salnotes)': '7Hz-Salnotes',
  '7hz/salnotes': '7Hz-Salnotes',
  // Xenns with Chinese chars
  'xenns(弦仕音频)': 'Xenns',
  // Yongse with Chinese chars
  'yongse(扬仕)': 'Yongse',
  // ZhuLinNiao with Chinese chars
  'zhulinniao(竹林鸟)': 'ZhuLinNiao',
  // ShuYouSheng with Chinese chars
  'shuyousheng(树有声音频)': 'SeeAudio',
  // Reecho(YUSICON) variant
  'reecho(yusicon)': 'Reecho',
  // G.K → GK consolidation
  'g.k': 'GK',
  // 634 Ears → 634ears
  '634 ears': '634ears',
  // Letshouer variant (without proper casing)
  'letshouer': 'LETSHUOER',
  // 7hertz → 7Hz
  '7hertz': '7Hz',
  // EPOS×DROP
  'epos×drop': 'EPOS',
  // HAVIT with Chinese
  'havit(海威特)': 'HAVIT',
  // Bang&Olufsen
  'bang&olufsen': 'B&O',
};

// Build alias lookup (lowercase key → canonical)
const ALIAS_ENTRIES = Object.entries(BRAND_ALIASES)
  .map(([k, v]) => [k.toLowerCase(), v] as const)
  .sort((a, b) => b[0].length - a[0].length); // longest first

// Sort longest-first so "Audio-Technica" matches before "Audio"
export const BRANDS_SORTED = [...KNOWN_BRANDS].sort((a, b) => b.length - a.length);

// Build a set of canonical brand names (lowercase) for quick membership check
const KNOWN_BRANDS_LOWER = new Set(KNOWN_BRANDS.map((b) => b.toLowerCase()));

/**
 * Extract canonical brand from a product name.
 * Returns null if the brand would be junk.
 * Brands from KNOWN_BRANDS are always trusted (never null).
 */
export function extractBrand(name: string): string | null {
  const nameLower = name.toLowerCase();

  // 1. Check aliases first (handles "64audio" → "64 Audio", "campfire" → "Campfire Audio", etc.)
  for (const [aliasLower, canonical] of ALIAS_ENTRIES) {
    if (nameLower.startsWith(aliasLower)) {
      return canonical;
    }
  }

  // 2. Check known brands (prefix match, case-insensitive)
  for (const brand of BRANDS_SORTED) {
    if (nameLower.startsWith(brand.toLowerCase())) {
      // Matched a known brand — always return it (even if short like "KZ", "LZ", "VE")
      return brand;
    }
  }

  // 3. Fallback: first word — but only if it looks like a real brand
  const firstWord = name.split(/\s+/)[0] || name;
  if (isJunkBrand(firstWord)) return null;
  if (firstWord.length <= 2 && !KNOWN_BRANDS_LOWER.has(firstWord.toLowerCase())) return null;
  return firstWord;
}
